version: '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/docker-entrypoint-initdb.d/
    restart: always
  
  api:
    build: .
    ports:
      - 8000
    restart: unless-stopped
    depends_on:
      - db
      
  lb:
    image: dockercloud/haproxy
    links:
      - api
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


